name: test pull request

on:
  pull_request:
    types: [opened, edited, ready_for_review, reopened]

env:
 JAVA_HOME: /usr/lib/jvm/java-21-openjdk/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install -Ddockerfile.skip -DdockerCompose.skip -Djib.skip"

